// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpkemqgiqojxofcgczar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwa2VtcWdpcW9qeG9mY2djemFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzc1MTUsImV4cCI6MjA2ODk1MzUxNX0.zlwLLaUY1sNpCQ3cO29aiPg2F2sOlrmE2TcXh8oYOKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});